name: DSE Stock Automation

on:
  schedule:
    - cron: '0 7 * * *' # Runs at 10AM Tanzania time (7AM UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install gspread google-auth pandas requests lxml

    - name: Install additional dependencies
      run: |
        pip install gspread google-auth pandas requests lxml scikit-learn yfinance joblib

    - name: Train model (weekly)
      run: |
        python predict_stock.py --train
      if: github.event_name == 'schedule' && github.event.schedule == '0 7 * * 1'  # Every Monday

    - name: Decode service account key
      run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}" | base64 -d > service_account.json

    - name: Run DSE bot
      env:
       GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
       TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
       TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python dse_bot.py
    
    - name: System Diagnostics
      run: |
        python -c "import pandas as pd; print(pd.show_versions())"
        df -h
        free -m
