name: DSE Stock Automation

on:
  schedule:
    - cron: '0 7 * * *' # Runs at 10AM Tanzania time (7AM UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
       pip install gspread google-auth pandas requests lxml scikit-learn yfinance joblib

    - name: Decode service account key
      run: echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_B64 }}" | base64 -d > service_account.json

    - name: Run DSE bot
      env:
       GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
       TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
       TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python dse_bot.py
        python scrapers/dse_reports_scraper.py
    - name: Install dependencies
      run: |
       pip install --upgrade pip
       pip install scikit-learn yfinance pandas joblib pandas-ta
       pip freeze > requirements.txt
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install scikit-learn==1.3.0 yfinance==0.2.18 pandas==2.0.3 joblib==1.3.2 pandas-ta==0.3.14b0
        pip list | grep -E "scikit-learn|yfinance|pandas|joblib"
        pip freeze > requirements.txt
        pip install requests beautifulsoup4
        pip install pdfplumber
        pip install requests beautifulsoup4 pdfplumber pandas openpyxl
        pip install schedule

